services:
  api:
    image: fumin89642/waffle-toy-project:latest
    container_name: waffle-toy-project
    restart: always
    env_file:
      - .env.prod
    expose:
      - "8000"
    command: ["uvicorn", "carrot.main:app", "--host", "0.0.0.0", "--port", "8000"]

  nginx:
    image: nginx:1.29-alpine
    container_name: nginx-proxy
    restart: always
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # nginx 설정
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/fastapi.conf:/etc/nginx/conf.d/fastapi.conf:ro

      # letsencrypt 인증서 마운트(읽기 전용)
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - web

networks:
  web:
    driver: bridge
